-- AlterTable
ALTER TABLE "EnderecoEmpresa" ALTER COLUMN "logradouro" SET DATA TYPE VARCHAR(40),
ALTER COLUMN "complemento" SET DATA TYPE VARCHAR(100),
ALTER COLUMN "cidade" SET DATA TYPE VARCHAR(50);

-- AlterTable
ALTER TABLE "EnderecoRepresentante" ALTER COLUMN "cidade" SET DATA TYPE VARCHAR(50);

-- AlterTable
ALTER TABLE "Representante" ALTER COLUMN "nome" SET DATA TYPE VARCHAR(200),
ALTER COLUMN "profissao" SET DATA TYPE VARCHAR(60),
ALTER COLUMN "cpf" SET DATA TYPE VARCHAR(14);
